name: WildLandsPlugin
version: 1.1
main: me.cojam.wildlands.WildLandsPlugin
api-version: 1.20
commands:
  wildlandsreload:
    description: Перезагрузка approved players и respawn таймингов
    usage: /wildlandsreload
    permission: wildlands.reload
    permission-message: У тебя нет прав на это