name: WildLandsPlugin
version: ${project.version}
main: me.cojam.wildlands.WildLandsPlugin
api-version: 1.21.11
commands:
  wildlandsreload:
    description: Перезагрузка approved players и respawn таймингов
    usage: /wildlandsreload
    permission: wildlands.reload
    permission-message: У тебя нет прав на это