name: Build Plugin

run-name: Build Plugin (${{ github.head_ref || github.ref_name }})

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    
    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Get plugin version
      id: get_version
      run: echo "PLUGIN_VERSION=$(grep -m 1 '<version>' pom.xml | sed 's/.*<version>\(.*\)<\/version>.*/\1/' | xargs)" >> $GITHUB_OUTPUT

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload Plugin Artifact
      uses: actions/upload-artifact@v6
      with:
        name: WildLandsPlugin-${{ steps.get_version.outputs.PLUGIN_VERSION }}
        path: target/*.jar
